function setTheme(theme) {
    const root = document.documentElement;
    const footer = document.querySelector("footer");
    const header = document.querySelector("header");
    const form = document.querySelector("form");
    if(theme === "dark") {
        root.style.setProperty('background', "var(--dark-background-color)");
        root.style.setProperty('color', "white");
        if(footer) {
            footer.style.setProperty('background-color', "lightseagreen");
        }
        if(header){
            header.style.setProperty('background-color', "var(--my-header-color-dark)");
        }
        form.style.setProperty('background-color', "lightgrey");
    }
    else {
        root.style.setProperty('background', "var(--light-background-color)");
        root.style.setProperty('color', "black");
        if(footer) {
            footer.style.setProperty('background-color', "orange");
        }
        if(header){
            header.style.setProperty('background-color', "var(--my-header-color)");
        }
        form.style.setProperty('background-color', "lightblue");
    }
}

function toggleTheme() {
    const currTheme = localStorage.getItem("theme") || "light";
    const newTheme = currTheme === "light" ? "dark": "light";
    localStorage.setItem("theme", newTheme);
    setTheme(newTheme);
}

function setSavedTheme() {
    const savedTheme = localStorage.getItem("theme");
    if(savedTheme) {
        setTheme(savedTheme);
        document.getElementById("themeToggle").checked = (savedTheme === "dark");
    }
}

document.addEventListener("DOMContentLoaded", setSavedTheme);

const localData = [
    {
        title: "California Housing Project",
        img: "/assets/CAHousingProj.png",
        alt: "Screenshot of a Google Colab notebook displaying EDA from a machine learning project.",
        desc: "In this project, I analyzed California Housing Prices based on factors like geographic area, house size, median income, etc. using a machine learning model that predicted the price of a house based on the aforementioned factors.",
        link: "https://colab.research.google.com/drive/1-bKBLW9ZAL_WHB8FuWlP39oS3Vh8escl?usp=sharing"
    },
    {
        title: "Wardrobe Recommendation System",
        img: "assets/WardrobeImg.png",
        alt: "Screenshot of a website showing the current weather for the user's location and a response generated by an LLM recommending what the user should wear based on the weather and the user's wardrobe.",
        desc: "Built a website where a user can check the weather in their location and get wardrobe recommendations from an LLM based on the weather and the user's wardrobe. The user can also create an account, add, remove, and edit wardrobe items, add real-time temperature and pressure sensors, and view a real-time graph of environmental data. Front-end coded with HTML and JavaScript, back-end coded with Python. Microcontroller code written in C++. Built with Docker.",
        link: "https://tech-assignment-final-project-pain-train.onrender.com/index"
    },
    {
        title: "Snake with Arduino",
        img: "assets/snake.png",
        alt: "Screenshot of the classic video game Snake.",
        desc: "Programmed the game Snake with C and an Arduino microcontroller. Made using Atmel AVR and custom libraries.",
        link: "https://www.youtube.com/watch?v=YVADGBSmJvo"
    }
];

function renderCards(dataArray) {
    const container = document.getElementById("cards-container");
    container.innerHTML = "";


    dataArray.forEach(element => {
        const card = document.createElement("project-card");
        card.setAttribute("title",element.title);
        card.setAttribute("img",element.img);
        card.setAttribute("alt",element.alt);
        card.setAttribute("desc",element.desc);
        card.setAttribute("link",element.link);

        container.appendChild(card);
    });
}

localStorage.setItem("projects",JSON.stringify(localData));

document.getElementById("loadLocal").addEventListener("click", () => {
    const json = localStorage.getItem("projects");
    const data = JSON.parse(json);
    renderCards(data);
});

document.getElementById("loadRemote").addEventListener("click", async() => {
    const res = await fetch("https://my-json-server.typicode.com/mkusnierzucsd/Matthew-Kusnierz-Portfolio/remoteData");
    const data = await res.json();
    renderCards(data);
});